### ISSUE TITLE
Installing mtbassist causes intellisense to misidentify stddtype format specifiers

### ISSUE THREAD

**Issue by petertorelli** [sjcbulldog/mtbassist#47]
Problem: Installing MTBASSIST causes Intellisense to incorrectly identify the types of stddints, resulting in many warning highlights. (It's the classic "Intellisense doesn't match the compiler" headache.)

System: macOS 26.
MTB Version: 3.6

Steps to reproduce:

1. Delete all extensions and vscode configuration from user's home `rm -rf ~/.vscode`
2. Delete `./.vscode` and `*.code-workspace` from the project folder
3. Run `make vscode` from the project folder
5. Open the workspace: `code <proj>.code_workspace`
6. Create a file "uint.c" containing this:
```
#include <inttypes.h>
#include <stdio.h>

uint32_t bar = 0ul;

void
test(void)
{
    printf("%lu\n", bar);
}
```
9. Run `make build` there should be no problems.
10. Install only Intellisense extension
11. Note that when you hover it identifies `uint32_t` as `unsigned long` and there are no warnings in the intellisense annotations regarding the `printf` format specifier type.
12. Install "ModusToolbox Assistant"
13. `printf` now shows an intellisense warning that `bar` is type `unsigned int`, and that `%lu` is the wrong format specifier. It still compiles fine, but if I change to `%u` to make Intellisense happy, the compiler now throws a warning.
14. Next I ran both "Fix" suggestions in MTB Assist main panel, reset Intellisense, but the warnings are still there (and restart Code)

Somehow Intellisense thinks `arm-none-eabi/include/machine/_default_types.h` usage of  `__UINT32_TYPE__` (the root macro) is no longer `long` after installing MTB Assist. The Intellisense C/C++ Log is not helpful.

Observations:

* All the paths in the c_cpp_preferences.json that MTB creates point to the correct MTB Arm compiler, and intellisense is following the correct #includes until it gets to the very last macro. Compiler type is "gcc-arm" in the JSON (since MTB created it). Forcing intellsense globally to use the MTB GCC_ARM path also does not work.

* Deleting the local project `.vscode` does not fix it, nor does uninstalling MTBAssist, I have to nuke `~/.vscode` and reinstall Intellisense to restore the correct functionality.

* I only recently updated MTBASSIST on my mac, I don't know what version I had before, unfortunately. (I'll try this on Windows & Linux to see if the same thing happens.)

* Note that using:

```
#include <inttypes.h>

printf("%" PRIu32 "\n", x);
```

...makes both Intellisense and the compiler happy, but who really uses those! ;-)

What else does MTBAssist change globally that might causes the local project's ".vscode/c_cpp_properties.json" to be over-ridden?

**Comment by sjcbulldog** [comment]
I believe this is fixed with the recent intellisense changes.  Please reopen if not.

**Comment by petertorelli** [comment]
Still seeing it. I deleted my ~/.vscode, and installed just MTBAssistant. (I'm now on a windows machine using a PSOC Edge device, too.)

Here's a screenshot showing Intellisense disagreeing with the compiler output. I also set the cm33_ns project as the "Intellisense" project (via checkbox).

<img width="1270" height="1235" alt="Image" src="https://github.com/user-attachments/assets/0981e4d8-7e3b-48ba-84a5-777ec2bba7d4" />


`usec` (line 321) is `uint32_T` and so is `psa_algorithm_t` (line 318):

```
typedef uint32_t psa_algorithm_t;
```

**Comment by petertorelli** [comment]
[PSOC_Edge_MBEDTLS_PSA_Crypto.tar.gz](https://github.com/user-attachments/files/23966024/PSOC_Edge_MBEDTLS_PSA_Crypto.tar.gz)
